### ISSUE TITLE
Config 파일 NextJS 표준에 맞게 재구성

### ISSUE THREAD

**Issue by argon1025** [TIL-Log-lab/Tilog-web-node-v2#42]
# ![기타](https://img.shields.io/badge/기타사항-else-green?style=for-the-badge&logo=GitHub&logoColor=white)

## 자세한 내용
(https://nextjs.org/docs/api-reference/next.config.js/environment-variables)

**Comment by MINJE-98** [comment]
.env를 사용합니다.
