### ISSUE TITLE
코드리뷰 기록

### ISSUE THREAD

**Issue by argon1025** [TIL-Log-lab/Tilog-web-node-v2#43]
# ![오류](https://img.shields.io/badge/오류발생-error-red?style=for-the-badge&logo=Cachet&logoColor=white)

## 자세한 내용
- 테크아이콘 constants로 이동및 병합
- Styles 불필요한 파일 정리
- _app.tsx 놀라움 주는 코드 정리
```
TILogApp.getInitialProps = async (context: AppContext) => {
  const { ctx } = context;
  if (!(ctx.req && ctx.res)) return { pageProps: {} };

  const session = await getIronSession(ctx.req, ctx.res, cookieConfig);
  return { pageProps: session };
};
```
- export const AccessTokenContext = createContext<AccessTokenInterface|null>(null);
- setAccessToken("");
- else if 사용
```
} else {
        if (error.response?.status === 401) {
```

- interface를 사용합시다
```
export async function getServerSideProps(context: {
  req: {
    cookies: {
      refreshToken: GetAccessTokenUsingRefreshTokenResponse;
    };
  };
}) {
```
- 타입 정의, 보내고, 받는거 확실하게 할것 -> 작업할 때 다른 구현파일 참조 한다 싶으면 아 잘못했구나 생각하기

**Comment by MINJE-98** [comment]
테크아이콘 constants로 이동및 병합
Styles 불필요한 파일 정리

위의 리뷰가 #44 로 분리되었습니다.

**Comment by MINJE-98** [comment]
#48에서 코드리뷰 반영으로 인해 이슈를 닫습니다.
